FROM --platform=linux/arm64 python:3.8-alpine

WORKDIR /opt
COPY . /opt/jwt_tool
WORKDIR /opt/jwt_tool
RUN apk add --no-cache gcc musl-dev linux-headers
RUN pip install --no-cache-dir -r requirements.txt
ENTRYPOINT ["python3","jwt_tool.py"]
